
# 06_Growth_Rate_Feature_Engineering.ipynb

Adds a new **growth_rate** feature to the SES framework.

Formula:

`growth_rate = future_interest - current_usage`

This captures momentum and rewards skills with stronger future demand relative to current adoption.

## Growth Rate Feature Selection

Three candidate growth metrics were evaluated:

1. growth_v1 = future_interest - current_usage
2. growth_v2 = (future_interest - current_usage) × future_interest
3. growth_v3 = future_interest / (current_usage + 0.05)

After comparing rankings, growth_v2 was selected because it balances future demand and momentum while avoiding excessive inflation of low-adoption niche skills.

In [22]:

import pandas as pd
import numpy as np

df = pd.read_csv('../Generated Datasets/master_skill_dataset_v6.csv')

print(df.shape)
df.head()

(35, 7)

,skill,linkedin_demand,salary_premium,current_usage,future_interest,future_score,global_adoption_score
0,aws,0.502949,0.571429,0.591886,0.686924,0.640658,0.892169
1,azure,0.288271,0.497905,0.342740,0.392354,0.435488,0.855730
2,c#,0.188676,0.462857,0.435240,0.492004,0.454085,0.923221
3,c++,0.265800,0.837857,0.368799,0.414020,0.492355,0.892499
4,django,0.015208,0.527619,0.155633,0.189361,0.272566,0.892766

In [23]:
# Version 1
# Future Interest - Current Usage

df['growth_v1'] = (
    df['future_interest']
    - df['current_usage']
)

In [24]:
# Version 2 (Best Choice)
# Momentum × Future Demand

df['growth_v2'] = (
    df['future_interest']
    - df['current_usage']
) * df['future_interest']

In [25]:
# Version 3
# Future / Current Ratio

df['growth_v3'] = (
    df['future_interest']
    /
    (df['current_usage'] + 0.05)
)

In [26]:

# Normalize all versions

for col in [
    'growth_v1',
    'growth_v2',
    'growth_v3'
]:

    df[col] = (
        df[col]
        - df[col].min()
    ) / (
        df[col].max()
        - df[col].min()
    )

print("\nTOP 10 - GROWTH V1")
display(
    df[
        ['skill','growth_v1']
    ].sort_values(
        'growth_v1',
        ascending=False
    ).head(10)
)

print("\nTOP 10 - GROWTH V2")
display(
    df[
        ['skill','growth_v2']
    ].sort_values(
        'growth_v2',
        ascending=False
    ).head(10)
)

print("\nTOP 10 - GROWTH V3")
display(
    df[
        ['skill','growth_v3']
    ].sort_values(
        'growth_v3',
        ascending=False
    ).head(10)
)

TOP 10 - GROWTH V1

         skill  growth_v1
28        rust   1.000000
9           go   0.738633
21  postgresql   0.597204
12  kubernetes   0.577972
5       docker   0.574859
34  typescript   0.452217
23      python   0.418034
27       redis   0.417252
33  tensorflow   0.368194
0          aws   0.346505

TOP 10 - GROWTH V2

         skill  growth_v2
28        rust   1.000000
5       docker   0.797950
21  postgresql   0.777826
9           go   0.649705
23      python   0.557097
34  typescript   0.530767
12  kubernetes   0.514327
0          aws   0.393336
27       redis   0.367412
26       react   0.338381

TOP 10 - GROWTH V3

         skill  growth_v3
28        rust   1.000000
9           go   0.759202
12  kubernetes   0.583688
33  tensorflow   0.509233
27       redis   0.481305
21  postgresql   0.479430
5       docker   0.462379
34  typescript   0.442755
17     next.js   0.441200
23      python   0.420693

In [27]:
df['growth_rate'] = df['growth_v2']

df[['skill','growth_rate']].sort_values('growth_rate',ascending=False).head(20)

         skill  growth_rate
28        rust     1.000000
5       docker     0.797950
21  postgresql     0.777826
9           go     0.649705
23      python     0.557097
34  typescript     0.530767
12  kubernetes     0.514327
0          aws     0.393336
27       redis     0.367412
26       react     0.338381
17     next.js     0.301263
15     mongodb     0.300913
31         sql     0.300144
2           c#     0.296059
33  tensorflow     0.287588
8          gcp     0.283955
1        azure     0.274024
18     node.js     0.272587
3          c++     0.272088
6      fastapi     0.252123

In [28]:
feature_cols = [
    'linkedin_demand',
    'salary_premium',
    'current_usage',
    'future_interest',
    'global_adoption_score',
    'growth_rate'
]

In [29]:
df = df[[
        'skill',
        'linkedin_demand',
        'salary_premium',
        'current_usage',
        'future_interest',
        'global_adoption_score',
        'growth_rate']]

df.to_csv('../Generated Datasets/master_skill_dataset_v7.csv',
    index=False
)

print(df.shape)
print("Saved: master_skill_dataset_v7.csv")

(35, 7)
Saved: master_skill_dataset_v7.csv